import Head from "next/head";
import { Inter } from "@next/font/google";
import homeStyles from "../styles/home.module.scss";
import { Button, Center, Container } from "@mantine/core";
import { SpacesGrid } from "../components/spacesGrid";
import { useAppSelector } from "../store/store.hooks";
import { selectSpaces } from "../store/slices/spacesSlice";
import { CreateSpaceButton } from "../components/createSpaceButton";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const spaces = useAppSelector(selectSpaces);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container className={homeStyles.mainContainer} size="md">
        <CreateSpaceButton />
        <SpacesGrid spaces={spaces} />
      </Container>
    </>
  );
}
